# Jekyll configuration file
# see: https://jekyllrb.com/docs/configuration/

title: Auth0 CLI
description: >-
  Build, manage and test your Auth0 integrations from the command line.
baseurl: "/auth0-cli"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: auth0
github_username: auth0
github_repo: auth0-cli

# Build settings
remote_theme: just-the-docs/just-the-docs@v0.4.1

search_enabled: true
favicon_ico: "/assets/images/favicon.png"

aux_links:
  "Auth0 CLI on GitHub":
    - "//github.com/auth0/auth0-cli"

callouts:
  warning:
    color: yellow